<div class="slider-wrapper">
    <div id="slideshow" class="nivoSlider"> 
        <a href="#">
            <img src="hinhanh/slider/slider-1.jpg" alt="slideshow-1" width="920" height="300" />
        </a> 
        <a href="#">
            <img src="hinhanh/slider/slider-2.jpg" alt="slideshow-2" width="920" height="300" />
        </a> 
        <a href="#">
            <img src="hinhanh/slider/slider-3.jpg" alt="slideshow-3" width="920" height="300" />
        </a> 
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#slideshow').nivoSlider();
    });
</script>